# Generated by Django 3.2 on 2021-04-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_name', models.CharField(max_length=200)),
                ('menu_item_description', models.CharField(max_length=200)),
                ('menu_item_price', models.IntegerField(default=0)),
            ],
        ),
    ]
