# Generated by Django 3.2 on 2021-05-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=2)),
                ('num_people', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('booked', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
