# Generated by Django 3.2 on 2021-05-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_reservationslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationslot',
            name='name',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
