# Generated by Django 3.2 on 2021-05-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_reservationslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='item_name',
            field=models.CharField(default='00000', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
    ]
