# Generated by Django 3.2 on 2021-05-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210501_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_removed',
            field=models.BooleanField(default=False),
        ),
    ]
