# Generated by Django 3.2 on 2021-05-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_order_item_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_number',
            field=models.IntegerField(default=1),
        ),
    ]
