# Generated by Django 3.2 on 2021-05-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_order_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
