# Generated by Django 3.2 on 2021-05-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_reservationslot_name'),
        ('website', '0010_alter_order_item_price'),
    ]

    operations = [
    ]
