# Generated by Django 3.2 on 2021-05-03 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_merge_20210503_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationslot',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.restaurant'),
        ),
    ]
