# Generated by Django 3.2 on 2021-05-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_reservationslot_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationslot',
            name='restaurant',
        ),
    ]
