# Generated by Django 3.2 on 2021-05-06 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_merge_20210503_1830'),
        ('website', '0016_reservationslot_restaurant'),
    ]

    operations = [
    ]
