# Generated by Django 3.2 on 2021-05-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_order_item_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_order',
            field=models.CharField(default='NA', max_length=1000),
        ),
    ]
