# Generated by Django 3.2 on 2021-05-04 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='table',
            name='restaurant',
        ),
    ]
