# Generated by Django 3.2 on 2021-05-05 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20210504_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='order',
        ),
    ]
